ENTER_FULL_NAME = "Please enter your full name"
ENTER_SIGNUP_EMAIL = "Email is required"
ENTER_SIGNUP_PASSWORD = "Password is required"
DASHBOARD = "dashboard"
ENTER_SIGNIN_EMAIL = "Please enter your email address"
ENTER_SIGNIN_PASSWORD = "Please enter your password"