ENTER_FULL_NAME = "Please enter your full name"

ENTER_SIGNUP_EMAIL = "Email is required"
ENTER_SIGNUP_PASSWORD = "Password is required"
DASHBOARD = "dashboard"
ENTER_SIGNIN_EMAIL = "Please enter your email address"
ENTER_SIGNIN_PASSWORD = "Please enter your password"
ENTER_CURRENT_PASSWORD = "Current password is required!"
ENTER_NEW_PASSWORD = "New password is required!"
ENTER_CONFIRM_PASSWORD = "Confirm password is required!"
CHANGE_PASSWORD_SUCCESS_MESSAGE= "Password changed successfully"
SUCCESS_TOASTER_MESSAGE_PROFILE_UPDATE="User updated successfully"